# Generated by Django 6.0.1 on 2026-01-29 12:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=100, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('telefonnummer', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Telefonnummer muss im Format eingegeben werden: '+999999999'. Bis zu 15 Ziffern erlaubt.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefonnummer')),
                ('strasse', models.CharField(max_length=200, verbose_name='Straße')),
                ('plz', models.CharField(max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(max_length=100, verbose_name='Ort')),
                ('land', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('datenschutz_akzeptiert', models.BooleanField(default=False, verbose_name='Datenschutzerklärung unterschrieben')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10, unique=True, verbose_name='Raumnummer')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('kapazitaet', models.IntegerField(default=1, verbose_name='Kapazität')),
                ('ist_aktiv', models.BooleanField(default=True, verbose_name='Ist aktiv')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
                'ordering': ['nummer'],
            },
        ),
        migrations.CreateModel(
            name='Raumtyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('typ', models.CharField(choices=[('EZ', 'Einzelzimmer'), ('DZ', 'Doppelzimmer'), ('SU', 'Suite')], default='EZ', max_length=2, verbose_name='Typ')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('preis_pro_nacht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis pro Nacht')),
            ],
            options={
                'verbose_name': 'Raumtyp',
                'verbose_name_plural': 'Raumtypen',
            },
        ),
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anreise_datum', models.DateField(verbose_name='Anreise Datum')),
                ('abreise_datum', models.DateField(verbose_name='Abreise Datum')),
                ('checkin_zeit', models.TimeField(default='14:00', verbose_name='Check-in Zeit')),
                ('checkout_zeit', models.TimeField(default='11:00', verbose_name='Check-out Zeit')),
                ('anlass', models.CharField(max_length=200, verbose_name='Anlass')),
                ('art_der_buchung', models.CharField(max_length=100, verbose_name='Art der Buchung')),
                ('status', models.CharField(choices=[('optimierung', 'Optimierung'), ('bestaetigt', 'Bestätigt'), ('storniert', 'Storniert')], default='optimierung', max_length=20, verbose_name='Status')),
                ('buchungsnummer', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Buchungsnummer')),
                ('anzahl_teilnehmer', models.IntegerField(default=1, verbose_name='Anzahl Teilnehmer')),
                ('anzahl_naechte', models.IntegerField(blank=True, null=True, verbose_name='Anzahl Nächte')),
                ('veranstalter_name', models.CharField(blank=True, max_length=200, verbose_name='Veranstalter Name')),
                ('veranstalter_kontakt', models.CharField(blank=True, max_length=200, verbose_name='Veranstalter Kontakt')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_buchungen', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='buchungen.kunde', verbose_name='Kunde')),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungen', to='buchungen.raum', verbose_name='Raum')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Belegungsprotokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leistung', models.CharField(max_length=200, verbose_name='Leistung')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('anzahl', models.IntegerField(default=1, verbose_name='Anzahl/Menge')),
                ('einzelpreis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis')),
                ('gesamtbetrag', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Gesamtbetrag')),
                ('schaden_vorher', models.TextField(blank=True, verbose_name='Schaden vorher')),
                ('schaden_nachher', models.TextField(blank=True, verbose_name='Schaden nachher')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('buchung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buchungen.buchung', verbose_name='Buchung')),
            ],
            options={
                'verbose_name': 'Belegungsprotokoll',
                'verbose_name_plural': 'Belegungsprotokolle',
            },
        ),
        migrations.AddField(
            model_name='raum',
            name='raumtyp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raeume', to='buchungen.raumtyp', verbose_name='Raumtyp'),
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsnummer', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Rechnungsnummer')),
                ('rechnungsdatum', models.DateField(default=django.utils.timezone.now, verbose_name='Rechnungsdatum')),
                ('faelligkeitsdatum', models.DateField(verbose_name='Fälligkeitsdatum')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('fertig', 'Fertig'), ('bezahlt', 'Bezahlt')], default='entwurf', max_length=20, verbose_name='Status')),
                ('gesamtbetrag', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gesamtbetrag')),
                ('kommentar', models.TextField(blank=True, verbose_name='Kommentar')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('buchung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechnungen', to='buchungen.buchung', verbose_name='Buchung')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Rechnungsposten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=200, verbose_name='Beschreibung')),
                ('menge', models.IntegerField(default=1, verbose_name='Menge')),
                ('einzelpreis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis')),
                ('gesamtpreis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Gesamtpreis')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posten', to='buchungen.rechnung', verbose_name='Rechnung')),
            ],
            options={
                'verbose_name': 'Rechnungsposten',
                'verbose_name_plural': 'Rechnungsposten',
            },
        ),
    ]
